export enum LoginFailureReason {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  USER_BLOCKED = 'USER_BLOCKED',
  USER_BANNED = 'USER_BANNED',
  USER_DELETED = 'USER_DELETED',
  TWO_FACTOR_INVALID = 'TWO_FACTOR_INVALID',
  TWO_FACTOR_EXPIRED = 'TWO_FACTOR_EXPIRED',
  TWO_FACTOR_ATTEMPTS_EXCEEDED = 'TWO_FACTOR_ATTEMPTS_EXCEEDED',
}
